version: '3.9'

services:
  db_django_menu:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=alique163
      - POSTGRES_DB=django-docker

  web:
    build: .
    command: python website/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-project
    ports:
      - 8080:8000
    depends_on:
      - db_django_menu
