# Generated by Django 4.1.7 on 2023-02-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_active',
        ),
    ]
